[package]
name = "vanity_contract_address"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
secp256k1 = { version = "0.27", features = ["rand-std"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }
rlp = "0.5"
hex = "0.4"
rayon = "1.7"
num_cpus = "1.13"